spring.datasource.url=jdbc:h2:mem:water_ressources-db
spring.h2.console.enabled=true

#Config MySql
#spring.datasource.url=jdbc:mysql://localhost:3306/water-ressources_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect