#spring.datasource.url=jdbc:mysql://192.168.1.6:3306/water-ressources_db?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://localhost:3306/mid_water_ressources-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect